[workspace]
members = [
    "betterncm-macro",
    "betterncm-loader",
    "betterncm-plugin-example",
    "betterncm-plugin-api",
    "cef-sys",
    "cef",
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
debug = false
strip = true
