[package]
name = "betterncm-plugin-api"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
betterncm-macro = { path = "../betterncm-macro" }
cef = { path = "../cef" }
cef-sys = { path = "../cef-sys" }
